### ISSUE TITLE
Editing a field with multiselect widget enabled causes exception

### ISSUE THREAD

**Issue by kducharm** [d8-contrib-modules/multiselect#3]
Clicking edit on a field under Manage Fields on a content type causes an exception when using the Multiselect widget:

---

Recoverable fatal error: Argument 1 passed to Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsWidgetBase::getOptions() must implement interface Drupal\Core\Entity\FieldableEntityInterface, instance of Drupal\options\Plugin\Field\FieldType\ListIntegerItem given, called in /Users/kdawg/workspace/d8.localhost.com/modules/contrib/multiselect/src/Plugin/Field/FieldWidget/MultiselectWidget.php on line 49 and defined in Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsWidgetBase->getOptions() (line 115 of core/lib/Drupal/Core/Field/Plugin/Field/FieldWidget/OptionsWidgetBase.php).
Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsWidgetBase->getOptions(Object) (Line: 49)
Drupal\multiselect\Plugin\Field\FieldWidget\MultiselectWidget->formElement(Object, 0, Array, Array, Object) (Line: 329)
Drupal\Core\Field\WidgetBase->formSingleElement(Object, 0, Array, Array, Object) (Line: 90)
Drupal\Core\Field\WidgetBase->form(Object, Array, Object) (Line: 303)
Drupal\Core\Field\FieldItemList->defaultValuesForm(Array, Object) (Line: 102)
Drupal\field_ui\Form\FieldConfigEditForm->form(Array, Object) (Line: 120)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 517)
Drupal\Core\Form\FormBuilder->retrieveForm('field_config_edit_form', Object) (Line: 276)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 79)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 128)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}() (Line: 577)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 129)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 102)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
call_user_func_array(Object, Array) (Line: 139)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 62)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 53)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 103)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 55)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 637)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

---

Found on a List (integer) field type on master branch with Drupal 8.0.5 core

**Comment by nerdstein** [comment]
Resolving.
